### ISSUE TITLE
When will the training code release? I can not wait to try it!

### ISSUE THREAD

**Issue by FrontierBreaker** [Algolzw/daclip-uir#1]
Awesome work!

**Comment by Algolzw** [comment]
Thanks!

The pretrained weight of DA-CLIP is [here](https://drive.google.com/file/d/1A6u4CaVrcpcZckGUNzEXqMF8x_JXsZdX/view?usp=sharing) and you can use it to generate degradation embeddings and clean image embeddings as the [example code](https://github.com/Algolzw/daclip-uir#da-clip-usage).

In addition, I'm planning to release the training code for DA-CLIP later this month.

**Comment by FrontierBreaker** [comment]
what's the gpu memory requirement for the training? (I only have a 12GB GPU but I would like to try it!

**Comment by FrontierBreaker** [comment]
I think this paper would be impactful for the community. : )

**Comment by Algolzw** [comment]
Thanks again for your interest! I train the DA-CLIP using 4 A100 GPUs (large batch size due to the contrastive learning) and an A100 for the downstream image restoration training. The training details can be found in the paper (Appendix B.1). 

Only a 12 GB GPU might be hard to train this model (but of course it is possible to change the batch size, patch size, and model parameters to fit your computer). Moreover, I will provide pretrained weights for the downstream diffusion model so you can easily test it.

**Comment by FrontierBreaker** [comment]
Got that. Thanks for your timely reply and suggestions! By the way, how about the training time on 4*A100 and the per-GPU memory cost for your experiments?

**Comment by Algolzw** [comment]
The training takes 3 hours and almost all GPU memories. :)

But the batch size is 784 x 4. You can try a smaller batch size such as 64 which would also work well.

**Comment by FrontierBreaker** [comment]
Got that. Thank you!
