### ISSUE TITLE
Some questions about your paper

### ISSUE THREAD

**Issue by zinuoli** [Algolzw/daclip-uir#45]
Hi, sorry for the distrubance again, I got some ambiguous points after reading your paper:

1. Do you train CLIP Controller and Restoration Model separtely or train they at the same time?
2. I saw you introduce learnable prompt at [this line](https://github.com/Algolzw/daclip-uir/blob/84a6ab6185bb7af9acacef88542411893bcb3ec6/universal-image-restoration/config/daclip-sde/models/modules/DenoisingUNet_arch.py#L135), which is smart. However, I notice you incorporate `prompt_embedding` by `t = t + prompt_embedding`, my question is why you integrate degradation type into `time step`, instead of  by cross attention like this `x = attn(x, context=image_context)`.
3. For the NAFNet there's no `time step`, how did you integrate `prompt_embedding` into NAFNet?

Something I didn't find answer in your paper (or I missed), sorry for interrupting you. Thank you for your great work.

**Comment by Algolzw** [comment]
Hi,

1. I train the two models separately.
2. I directly add the prompt_embedding to time_embedding for model efficiency since we already have cross-attentions for the image_context.
3. For the modified NAFNet (with time embeddings), you can refer to the Refusion's code [here](https://github.com/Algolzw/image-restoration-sde/blob/main/codes/config/deraining/models/modules/DenoisingNAFNet_arch.py).

**Comment by zinuoli** [comment]
Got it, thank you so much.😄
