### ISSUE TITLE
Seems to be working well only on test images

### ISSUE THREAD

**Issue by denisbondare** [Algolzw/daclip-uir#6]
I'm using Google Colab with gradio to test the project, and it seems it doesn't do almost anything on my custom images (I tried different degradations in my examples), it only adds some noise and that's it. It works very well only for the test images provided in the project. Is there possibly a mistake in [app.py](https://github.com/Algolzw/daclip-uir/blob/main/universal-image-restoration/config/daclip-sde/app.py) script or anywhere else in the pipeline for testing with custom images? Or maybe a pretrained model is so limited?

**Comment by Algolzw** [comment]
Hello, what's the image/degradation you want to test with our model? Like other deep learning based approaches our model might be limited by the training datasets which are specially collected from different image restoration tasks (as shown in our paper appendix A). It works well on some similar captured images but sometimes would also produce unsatisfied results due to the data distribution shifts.

**Comment by denisbondare** [comment]
I'm testing the same kinds of degradations as presented in the paper. Manually uncompleted, motion blurry, hazy, rainy. So if everything is right in the code and the model is actually pretrained to work in general, it should be fine, at least some examples should show similar quality of the results. So far I couldn't make it work on any images, not presented in the project itself. Does practically nothing except for some extra noise and unexpected behavior, like removing a random reflection on the picture. The problem might be in recognition of the degradation pattern, is there a possibility to choose it manually instead of using automatic recognition?

**Comment by Algolzw** [comment]
Okok, can you share some examples then I can test them on my server?

**Comment by denisbondare** [comment]
Here's a screenshot of my notebook, images I use and results I get. It seems the last one get some noise reduction treatment, but what confuses me the most is uncompleted examples. It does it so easily on the example images, but I tried it on several I made myself, and it seems it doesn't recognize it's an incomplete image.
![Screenshot_3](https://github.com/Algolzw/daclip-uir/assets/30900845/a98700cc-73be-4fc8-b97f-a50a2c653599)
![test1](https://github.com/Algolzw/daclip-uir/assets/30900845/bd6b80b3-79fb-4261-83da-54c13738c5ed)
![result1](https://github.com/Algolzw/daclip-uir/assets/30900845/e3fd567c-4e7c-4888-9277-357a13693fe3)
![test2](https://github.com/Algolzw/daclip-uir/assets/30900845/42f907d7-4643-4fc2-ae55-e3a8f321df06)
![result2](https://github.com/Algolzw/daclip-uir/assets/30900845/a08cdbdc-bbde-40ac-acbc-b7f92a3b66b2)
![test3](https://github.com/Algolzw/daclip-uir/assets/30900845/e18352e8-a661-48c5-b54f-6c8d84eb7e92)
![result3](https://github.com/Algolzw/daclip-uir/assets/30900845/d91263f9-e116-48fa-aaa9-8991475b1bc2)

**Comment by Algolzw** [comment]
Aha, I think the results on uncompleted images aren’t good because we only trained our model with face inpainting dataset. Maybe I can add more general images in training to improve the generalization ability. :)

**Comment by denisbondare** [comment]
I tried it on a face example, nothing like paper results.. If it's actually only a training problem than it definitely needs more training on bigger data, because for now the results in paper look very impressive, but seems that the pretrained model isn't ready for actual usage. Or at least some commentary in the manual about quite a restriction of a currently available pretrained model would be very useful to avoid confusion, otherwise seems kind of deceiving :( Thank you for your work, the results in paper are actually very good!
![Screenshot_4](https://github.com/Algolzw/daclip-uir/assets/30900845/c7b8088b-c4fd-4d8a-a901-2dd0cf2d5817)

![téléchargement (1)](https://github.com/Algolzw/daclip-uir/assets/30900845/9415fb94-6696-4b1f-a220-4a2210b7a344)

**Comment by Algolzw** [comment]
Yes I believe it’s a training problem since we only collected limited images for training and testing from other task-specific papers (as listed in the table). Most images in the same dataset are obtained by the same device or synthetic approach, which makes it currently hard to be used for real applications. (Unlike stable diffusion which uses billions of images from different websites to train their model.)

![2C352D2C-FABE-43D4-8AEC-4750EBD8E2A8](https://github.com/Algolzw/daclip-uir/assets/15884127/46f0cdcb-8a54-42f3-9935-46692cd6a06c)


However, the universal image restoration is still a under-explored problem and definitely deserves more exploration. I am happy to add your comments to my future work (more datasets, image sources, and degradations) and release the stronger version model.

Thanks!
